openapi: 3.1.0
info:
  title: analysis specification
  version: '1.0'
  summary: Analysis Specification for Meta-analysis
  description: api to create a meta-analysis specification
servers:
  - url: 'http://localhost:81'
    description: test
paths:
  /datasets/:
    get:
      summary: GET a list of datasets
      tags:
        - datasets
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/dataset'
                    - $ref: ./neurostore-openapi.yml#/components/schemas/read-only
      description: Get a list of datasets.
      parameters:
        - $ref: ./neurostore-openapi.yml#/components/parameters/search
        - $ref: ./neurostore-openapi.yml#/components/parameters/sort
        - $ref: ./neurostore-openapi.yml#/components/parameters/page
        - $ref: ./neurostore-openapi.yml#/components/parameters/desc
        - $ref: ./neurostore-openapi.yml#/components/parameters/page_size
    post:
      summary: POST/create a dataset
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dataset'
      tags:
        - datasets
      description: Create a dataset.
  '/datasets/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: GET a dataset
      tags:
        - datasets
      responses:
        '200':
          description: Dataset found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dataset'
                  - $ref: ./neurostore-openapi.yml#/components/schemas/read-only
              examples: {}
        '404':
          $ref: ./neurostore-openapi.yml#/components/responses/404
      description: Retrieve the information of a dataset with the matching dataset ID.
      parameters: []
    put:
      summary: PUT/update a dataset
      responses:
        '200':
          description: OK
        '422':
          $ref: ./neurostore-openapi.yml#/components/responses/422
      description: Update a dataset.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dataset'
      tags:
        - datasets
      security:
        - JSON-Web-Token: []
  /meta-analyses/:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/meta-analysis'
      description: ''
    parameters: []
    post:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/meta-analysis'
      description: create a meta-analysis
      security:
        - JSON-Web-Token: []
  '/meta-analyses/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/meta-analysis'
    put:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/meta-analysis'
      description: edit an existing meta-analysis
components:
  schemas:
    dataset:
      title: dataset
      type: object
      description: ''
      x-examples: {}
      properties:
        name:
          type: string
          description: ''
          nullable: true
        description:
          type: string
          nullable: true
        publication:
          type: string
          nullable: true
        doi:
          type: string
          nullable: true
        pmid:
          type: string
          nullable: true
        data:
          description: ''
          type: array
          items:
            $ref: ./neurostore-openapi.yml#/components/schemas/study
        user:
          type: string
          nullable: true
          readOnly: true
      required:
        - name
        - data
    algorithm:
      title: algorithm
      type: object
      properties:
        type:
          type: string
          enum:
            - coordinate
            - image
            - both
          description: 'whether the algorithm operates on coordinates, images, or both.'
        name:
          type: string
          description: name of the meta-analysis algorithm
          example: mkda
        parameters:
          type: object
          description: parameters of the algorithm (like kernel size)
    meta-analysis:
      title: meta-analysis
      type: object
      properties:
        dataset:
          $ref: '#/components/schemas/dataset'
        algorithm:
          $ref: '#/components/schemas/algorithm'
        annotation:
          $ref: '#/components/schemas/annotation'
    annotation:
      title: annotation
      type: object
      description: a dictionary whose keys represent columns and whose values are arrays with an entry for study in the dataset
  securitySchemes:
    JSON-Web-Token:
      type: http
      scheme: bearer
